### ISSUE TITLE
archlinux AttributeError: 'module' object has no attribute 'init'

### ISSUE THREAD

**Issue by noog** [xantares/nfc-bindings#1]
hello
i compiled the last version of python2-nfc
and i created a file with your example script
but when i execute it i have this error

python2 nfc.py 
Traceback (most recent call last):
  File "nfc.py", line 1, in <module>
    import nfc
  File "/home/xxx/nfc.py", line 2, in <module>
    context = nfc.init()
AttributeError: 'module' object has no attribute 'init'

**Comment by xantares** [comment]
hi,
that's weird, is your system up to date ?
the PKGBUILD i uploaded had an invalid comma in the arch field, it's fixed now.
