### ISSUE TITLE
[Question] emulate tag

### ISSUE THREAD

**Issue by JHuenerberg** [xantares/nfc-bindings#12]
Hi @xantares,

I want to emulate a tag and configure the attributes for the tag by hand.
I'm getting a type error when I try to set abtUid et cetera.
```
nt.nti.nai.abtUid = bytearray([0x00, 0x04, 0x00, 0x04, 0x00, 0x04, 0x00, 0x04, 0x00, 0x04])
```
Gives a ```argument 2 of type 'uint8_t [10]'``` error.
When I try to pass a uint8 array still crashes ```np.arange(10, dtype=np.uint8)```

Thank you very much in advance for your answer!

**Comment by xantares** [comment]
It wasnt listed in the possible input fields, see 3611530, you can add more when you need, patches welcome.
