### ISSUE TITLE
ModuleNotFoundError: No module named 'nfc'

### ISSUE THREAD

**Issue by k4linx** [xantares/nfc-bindings#16]
Hi

I cannot execute the quick_start_example. Here's what i get:

`Traceback (most recent call last):
  File "/home/pi/nfc-bindings/python/examples/quick_start_example.py", line 8, in <module>
    import nfc
ModuleNotFoundError: No module named 'nfc'`

I hope anybody can help me thanks

Regards

k4linx

**Comment by xantares** [comment]
was the compilation successful ?
where did you install it ?
logs ?

**Comment by k4linx** [comment]
Sorry false alarm. A reboot did the thing
