### ISSUE TITLE
Bindings not working with older swig.

### ISSUE THREAD

**Issue by lesbeben** [xantares/nfc-bindings#3]
Hi!
First of all, thank you for your work on this port.
I tried to install your bindings on kali linux (based on debian stable). The install runs smoothly, but when I try to run the example script from the readme, I get:
````
Traceback (most recent call last):
  File "./example.py", line 2, in <module>
    import nfc
  File "/home/beben/.local/lib/python2.7/site-packages/nfc.py", line 30, in <module>
    _nfc = swig_import_helper()
  File "/home/beben/.local/lib/python2.7/site-packages/nfc.py", line 26, in swig_import_helper
    _mod = imp.load_module('_nfc', fp, pathname, description)
ImportError: /home/beben/.local/lib/python2.7/site-packages/_nfc.so: undefined symbol: iso14443b_crc
```
I'm guessing this is a swig error, since kali is running 2.0.7, which is quite old. 
Do you know what the lowest compatible version of swig is ?
It might be a good idea to mention it in the readme!

Cheers.

**Comment by xantares** [comment]
Hi,
This one happened to me before, not sure if it's related to swig, are you sure you're using libnfc 1.7.1 or a git version ?

**Comment by lesbeben** [comment]
Hi, thanks for your reply!
I've tried swig 2.0.12 and 3.0.5, to no avail...
I am using the 1.7.1 release, straight from github, and python 2.7.3.
Cmake is 2.8.9
I installed with `cmake -DCMAKE_INSTALL_PREFIX=/usr .` foloowed by `sudo make install``
Sad thing is, your bindings and example work out of the box on my arch, but I can't figure out what debian lacks that might cause this...

**Comment by xantares** [comment]
you can try to compare the symbols available in the two .so in debian/arch with nm,
in my opinion debian is not really providing 1.7.1:
http://anonscm.debian.org/cgit/collab-maint/libnfc.git/tree/debian/libnfc5.symbols
i close this bug as it's rather a debian thing

**Comment by lesbeben** [comment]
All right, but like I said, I'm not using debian's libnfc but github's, since debian does not provide 1.7.1

**Comment by xantares** [comment]
lokks like 1.7.1 to me:
https://packages.debian.org/source/jessie/libnfc

anyway you're sure you're using the 1.7.1 tag ? or the master ?

**Comment by lesbeben** [comment]
Definitely using the 1.7.1, from the archive on the release page, however I noticed that libnfc.so does not have any symbols in it. Clearly the bug is not on your side, I apologize for bothering you!
